applications/entradas/urls.py
from django.urls import path
from . import views

app_name = "entrada_app"

urlpatterns = [
    path(
        'entradas/', 
        views.EntryListView.as_view(),
        name='entry-lista',
    ),     
    path(
        'entrada/<slug>/', 
        views.EntryDetailView.as_view(),
        name='entry-detail',
    ),  
]

applications/home/urls.py
#
from django.urls import path
from . import views

app_name = "home_app"

urlpatterns = [
    path(
        '', 
        views.HomePageView.as_view(),
        name='index',
    ), 
    path(
        'register-suscription', 
        views.SuscriberCreateView.as_view(),
        name='add-suscription',
    ), 
    path(
        'contact', 
        views.ContactCreateView.as_view(),
        name='add-contact',
    ), 
]

proyectobase/urls.py
"""
Proyecto Curso Django
"""
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
# seo
from django.contrib.sitemaps.views import sitemap
from applications.home.sitemap import (
    EntrySitemap,
    Sitemap,
)

urlpatterns_main = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.entradas.urls')),
    re_path('', include('applications.favoritos.urls')),
    # urls para ckeditor
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#objeto site map que genera xml
sitemaps = {
    'site':Sitemap(
        [
            'home_app:index'
        ]
    ),
    'entradas': EntrySitemap
}

urlpatterns_sitemap = [
    path(
        'sitemap.xml', 
        sitemap, 
        {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    )
]

urlpatterns = urlpatterns_main + urlpatterns_sitemap

applications/home/models.py
from django.db import models

# Create your models here.
from django.db import models
# apps terceros
from model_utils.models import TimeStampedModel
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.
class Home(TimeStampedModel):
    # Model para datos de la pantalla home
    title = models.CharField(
        'Nombre',
        max_length=30
    )
    description = RichTextUploadingField()
    about_title = models.CharField(
        'Titulo Nosotros',
        max_length=50
    )
    about_text = RichTextUploadingField()
    contact_email = models.EmailField(
        'email de contacto',
        blank=True,
        null=True
    )
    phone = models.CharField(
        'Telefono contacto', 
        max_length=20
    )
    
    class Meta:
        verbose_name = 'Pagina Principal'
        verbose_name_plural = 'Pagina Principal'
        
    def __str__(self):
        return self.title
    
    
class Suscribers(TimeStampedModel):
    # Suscripciones
    email = models.EmailField()
    
    class Meta:
        verbose_name = 'Suscriptor'
        verbose_name_plural = 'Suscriptores'
        
    def __str__(self):
        return self.email
    
class Contact(TimeStampedModel):
    # Formulario de Contacto
    full_name = models.CharField(
        'Nombres', 
        max_length=60
    )
    email = models.EmailField()
    message = models.TextField()
    
    class Meta:
        verbose_name = 'Contacto'
        verbose_name_plural = 'Mensajes'
        
    def __str__(self):
        return self.full_name

applications/home/forms.py
from dataclasses import field
from django import forms

# models
from .models import Suscribers, Contact

class SuscribersForm(forms.ModelForm):
    class Meta:
        model = Suscribers
        fields = (
            'email',
        )
        widgets = {
            'email': forms.EmailInput(
                attrs={
                    'placeholder': 'Correo Electonico...',
                }
            ),
        }
        
class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = (
            'full_name',
            'email',
            'message'
        )
        

applications/home/views.py
import datetime
#
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse

from django.views.generic import (
    TemplateView,
    CreateView
)
# app entrada
from applications.entradas.models import Entry
# models
from .models import Home
# forms
from .forms import SuscribersForm, ContactForm

class HomePageView(TemplateView):
    template_name = "home/index.html"

    
    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        # cargamos el home
        context["home"] = Home.objects.latest('created')
        # contexto de portada
        context["portada"] = Entry.objects.entrada_en_portada()
        # contexto para los articulos en home
        context["entradas_home"] = Entry.objects.entradas_en_home()
        # devuelve las ultimas 6 entradas recientes
        context["entradas_recientes"] = Entry.objects.entradas_recientes()
        # enviamos formulario de suscripcion
        context["form"] = SuscribersForm        
        return context
    
class SuscriberCreateView(CreateView):
    form_class = SuscribersForm
    success_url = '.'
    
class ContactCreateView(CreateView):
    form_class = ContactForm
    success_url = '.'

templates/home/base_home.html
{% extends "base.html" %}

{% load  static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/myblog.css' %}">
{% endblock css %}

{% block js %}

{% endblock js %}

templates/home/index.html
<!-- head para PC -->
{% extends "home/base_home.html" %}
{% load  static %}

{% block title %}
{{home.title}}
{% endblock title %}


{% block description %}
<meta name="description" content="{{home.description}}">
{% endblock description %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <!-- primer bloque del home -->
    <div class="grid-x grid-margin-x" style="margin-top: 1em;">
        <!-- bloque de blog principal -->
        <div class="cell small-12 large-6">
            <div class="card" style="width: 100%;">
                <a href="{% url 'entrada_app:entry-detail' portada.slug %}">
                    <img src=" {{ portada.image.url }}" style="height: 300px">
                </a>
                <div class="card-section">
                  <h4> <a href="{% url 'entrada_app:entry-detail' portada.slug %}"> {{ portada.title }} </a></h4>
                  <p>{{portada.resume|safe | truncatechars:150}}</p>
                  <a href="{% url 'entrada_app:entry-detail' portada.slug %}" class="button primary"> Leer Mas </a>
                </div>
            </div>
        </div>
        <!-- FIN bloque de blog principal -->

        <!-- bloque de blog principal -->
        <div class="cell small-12 large-6 grid-x grid-margin-x">            
            {% for entrada in entradas_home %}
            <div class="cell small-12 large-6">
                <div class="card" style="width: 100%;">
                    <a href="{% url 'entrada_app:entry-detail' portada.slug %}">
                        <img src="{{entrada.image.url}}" style="height: 120px;" style="width: 200px;">
                    </a>
                    <div class="card-section">
                      <h5>
                          <a href="{% url 'entrada_app:entry-detail' entrada.slug %}"> {{entrada.title | truncatechars:35 }} </a>
                      </h5>
                      <a href="{% url 'entrada_app:entry-detail' portada.slug %}" class="button primary"> Leer Mas </a>
                    </div>                    
                </div>
            </div>
            {% endfor %}
                
                       
        </div>
        <!-- FIN bloque de blog principal -->
    </div>
    <!-- FIN del primer bloque home -->

    <!-- segundo bloque pantalla home -->
    <div class="grid-x align-center" style="margin-top: 1em;">
        <div class="cell small-12 large-10 callout secondary">
            <h5>{{home.about_title}}</h5>
            <p>
                {{home.about_text|safe}}
            </p>

            <p>
                <button class="button" data-open="exampleModal2">Suscribirme</button>
            </p>

            <!-- This is the first modal -->
            <div class="reveal" id="exampleModal2" data-reveal style="width: 300px;">
                <p class="lead">Ingresa tu correo</p>
                <form class="grid-x grid-margin-x" method="post" action=" {% url 'home_app:add-suscription' %} "> {% csrf_token %}
                    <div class="cell small-12">
                        {{form.email}}
                    </div>
                    <div class="cell small-12">
                        <button type="submit" class="success button">Suscribirme</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
    <!-- FIN segundo bloque pantalla home -->


    <!-- tercer bloque home -->
    <div class="grid-x grid-margin-x align-center">
        <h3 class="cell">Articulos Recientes:</h3>
        
        {% for entrada in entradas_recientes %}
        <div class="cell small-6 large-4">
            <div class="card" style="width: 100%;">
                <a href="{% url 'entrada_app:entry-detail' entrada.slug %}">
                    <img src="{{entrada.image.url}}" style="height: 200px">
                </a>
                <div class="card-section">
                  <a href="{% url 'entrada_app:entry-detail' entrada.slug %}">{{entrada.title | truncatechars:40 }}</a>
                  <p>{{entrada.resume|safe | truncatechars:70 }}</p>
                  <a href="{% url 'entrada_app:entry-detail' entrada.slug %}" class="button primary">Leer Mas</a>
                </div>
            </div>
        </div>
        {% endfor %}
            
          
    </div>
    <!-- FIN tercer bloque -->
</div>
{% include "includes/footer.html" %}

{% endblock content %}