applications/entradas/urls.py
from django.urls import path
from . import views

app_name = "entrada_app"

urlpatterns = [
    path(
        'entradas/', 
        views.EntryListView.as_view(),
        name='entry-lista',
    ),     
    path(
        'entrada/<slug>/', 
        views.EntryDetailView.as_view(),
        name='entry-detail',
    ),  
]

applications/favoritos/urls.py
#
from django.urls import path


from . import views

app_name = "favoritos_app"

urlpatterns = [
    path(
        'perfil/', 
        views.UserPageView.as_view(),
        name='perfil',
    ),  
    path(
        'add-entrada/<pk>/', 
        views.AddFavoritos.as_view(),
        name='add-favoritos',
    ),
    path(
        'delete-entrada/<pk>/', 
        views.FavoritesDeleteView.as_view(),
        name='delete-favoritos',
    ),
]

applications/users/urls.py
from django.urls import path

from . import views

app_name = "users_app"
urlpatterns = [
    path(
        'register/', 
        views.UserRegisterView.as_view(),
        name='user-register'
    ),
    path(
        'login/',
        views.LoginUser.as_view(),
        name='user-login'
    ),
    path(
        'logout/',
        views.LogoutView.as_view(),
        name='user-logout'
    ),
    path(
        'update/',
        views.UpdatePasswordView.as_view(),
        name='user-update'
    ),
    # path(
    #     'user-verification/<pk>/',
    #     views.CodeVerificationView.as_view(),
    #     name='user-verification'
    # ),
]

proyectobase/urls.py
"""
Proyecto Curso Django
"""
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
# seo
from django.contrib.sitemaps.views import sitemap
from applications.home.sitemap import (
    EntrySitemap,
    Sitemap,
)

urlpatterns_main = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.entradas.urls')),
    re_path('', include('applications.favoritos.urls')),
    # urls para ckeditor
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#objeto site map que genera xml
sitemaps = {
    'site':Sitemap(
        [
            'home_app:index'
        ]
    ),
    'entradas': EntrySitemap
}

urlpatterns_sitemap = [
    path(
        'sitemap.xml', 
        sitemap, 
        {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    )
]

urlpatterns = urlpatterns_main + urlpatterns_sitemap

applications/favoritos/models.py
from django.conf import settings
from django.db import models
# apps terceros
from model_utils.models import TimeStampedModel
# 
from applications.entradas.models import Entry
from .managers import FavoritesManager

# Create your models here.

class Favorites(TimeStampedModel):
    # modelo para favoritos
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='user_favorites',
        on_delete=models.CASCADE,
    )
    entry = models.ForeignKey(
        Entry,
        related_name='entry_favorites',
        on_delete=models.CASCADE
    )
    
    objects = FavoritesManager()
    
    class Meta:
        unique_together = ('user', 'entry')
        verbose_name = 'Entrada Favorita'
        verbose_name_plural = 'Entradas Favotitas'
        
    def __str__(self):
        return self.entry.title

applications/favoritos/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
# 
from django.views.generic import (    
    View,
    ListView,
    DeleteView
)
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Favorites

# app
from applications.entradas.models import Entry

# Create your views here.
class UserPageView(LoginRequiredMixin, ListView):   
    template_name = "favoritos/perfil.html"
    context_object_name = 'entradas_user'
    login_url = reverse_lazy('users_app:user-login')
    
    def get_queryset(self):
        return Favorites.objects.entradas_user(self.request.user)
    
    
class AddFavoritos(LoginRequiredMixin, View):
    login_url = reverse_lazy('users_app:user-login')
    
    def post(self, request, *args, **kwargs):
        # recuperar el usuario
        usuario = self.request.user
        # recuperar el id de la entrada
        entrada = Entry.objects.get(id=self.kwargs['pk'])
        # registrar la entrada a favoritos
        Favorites.objects.create(
            user=usuario,
            entry=entrada,
        )
        
        return HttpResponseRedirect(
            reverse(
                'favoritos_app:perfil'
            )
        )
        

class FavoritesDeleteView(DeleteView):
    model = Favorites
    success_url = reverse_lazy('favoritos_app:perfil')
    
# para intentar solucionar el problema de llaves repetidas 
class AddFovoritosView(LoginRequiredMixin, View): 
    login_url = reverse_lazy('users_app:user-login') 
   
    def post(self, request, *args, **kwargs): 
      # recuperar el usuario 
        usuario = self.request.user 
        entrada = Entry.objects.get(id=self.kwargs['pk']) 
      # registramos favorito 
        try:
                Favorites.objects.create( user=usuario, entry=entrada, ) 
                return HttpResponseRedirect( reverse( 'favoritos_app:perfil', ) )
        
        except:
                return HttpResponseRedirect( reverse( 'favoritos_app:vista_error', ) )

templates/favoritos/base_favoritos.html
{% extends "base.html" %}

{% load  static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/myblog.css' %}">
{% endblock css %}

{% block js %}

{% endblock js %}

templates/favoritos/perfil.html
<!-- head para PC -->
{% extends "favoritos/base_favoritos.html" %}
{% load  static %}
{% block title %}
{{home.title}} - Perfil del Usuario
{% endblock title %}
{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x grid-margin-x align-center" style="margin-top: 1em;">
        <!-- bloque de datos de usuario -->
        <div class="cell small-12 large-4">
            <div class="callout primary border-none">
                <h5>{{ user.nombres }}</h5>
                <p>
                    <b>Email:</b> {{user.email}} <br> 
                    <b>Ocupacion:</b> {{user.ocupation}} <br> 
                    <b>Fecha de nacimiento:</b> {{user.date_birth}}<br> 
                <p>
                <a href="{% url 'users_app:user-update' %}" class="warning button">Editar Datos</a>
                <a href="{% url 'users_app:user-logout' %}" class="alert button">Salir</a>
                </p>                
            </div>
        </div>
        <!-- FIN bloque de datos de usuario -->


        <!-- bloque de articulos favoritos de usuario -->
        <div class="cell large-8 grid-x grid-margin-x align-center">
            {% for entrada in entradas_user %}
            <div class="cell small-12">
                <div class="card-favoritos">
                    <img class="card-favoritos-img" src="{{ entrada.entry.image.url }}">
                    <div class="card-favoritos-body">
                        <h3 class="card-favoritos-body-titulo">{{ entrada.entry.title }}</h3>
                        <p class="card-favoritos-body-text">{{ entrada.entry.resume | truncatechars:100 }}</p>
                        <form class="card-favoritos-body-actions" method="post" action="{% url 'favoritos_app:delete-favoritos' entrada.id %}"> {% csrf_token %}
                            <a class="success button" href="{% url 'entrada_app:entry-detail' entrada.entry.slug %}">Ver</a>                            
                            <button type="submit" class="button alert">Eliminar</button>
                        </form>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <!-- FIN bloque de articulos favoritos de usuario -->
    </div>
</div>
{% include "includes/footer.html" %}

{% endblock content %}