applications/entradas/urls.py
from django.urls import path
from . import views

app_name = "entrada_app"

urlpatterns = [
    path(
        'entradas/', 
        views.EntryListView.as_view(),
        name='entry-lista',
    ),     
    path(
        'entrada/<slug>/', 
        views.EntryDetailView.as_view(),
        name='entry-detail',
    ),  
]

applications/favoritos/urls.py
#
from django.urls import path


from . import views

app_name = "favoritos_app"

urlpatterns = [
    path(
        'perfil/', 
        views.UserPageView.as_view(),
        name='perfil',
    ),  
    path(
        'add-entrada/<pk>/', 
        views.AddFavoritos.as_view(),
        name='add-favoritos',
    ),
    path(
        'delete-entrada/<pk>/', 
        views.FavoritesDeleteView.as_view(),
        name='delete-favoritos',
    ),
]

applications/home/urls.py
#
from django.urls import path
from . import views

app_name = "home_app"

urlpatterns = [
    path(
        '', 
        views.HomePageView.as_view(),
        name='index',
    ), 
    path(
        'register-suscription', 
        views.SuscriberCreateView.as_view(),
        name='add-suscription',
    ), 
    path(
        'contact', 
        views.ContactCreateView.as_view(),
        name='add-contact',
    ), 
]

applications/users/urls.py
from django.urls import path

from . import views

app_name = "users_app"
urlpatterns = [
    path(
        'register/', 
        views.UserRegisterView.as_view(),
        name='user-register'
    ),
    path(
        'login/',
        views.LoginUser.as_view(),
        name='user-login'
    ),
    path(
        'logout/',
        views.LogoutView.as_view(),
        name='user-logout'
    ),
    path(
        'update/',
        views.UpdatePasswordView.as_view(),
        name='user-update'
    ),
    # path(
    #     'user-verification/<pk>/',
    #     views.CodeVerificationView.as_view(),
    #     name='user-verification'
    # ),
]

proyectobase/urls.py
"""
Proyecto Curso Django
"""
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
# seo
from django.contrib.sitemaps.views import sitemap
from applications.home.sitemap import (
    EntrySitemap,
    Sitemap,
)

urlpatterns_main = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.entradas.urls')),
    re_path('', include('applications.favoritos.urls')),
    # urls para ckeditor
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#objeto site map que genera xml
sitemaps = {
    'site':Sitemap(
        [
            'home_app:index'
        ]
    ),
    'entradas': EntrySitemap
}

urlpatterns_sitemap = [
    path(
        'sitemap.xml', 
        sitemap, 
        {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    )
]

urlpatterns = urlpatterns_main + urlpatterns_sitemap

templates/includes/footer.html
<footer>
  <div class="callout secondary">
    <div class="grid-x align-center">
        <h3 class="cell small-12 large-7">Formulario de Contacto:</h3>
        <form class="cell small-12 large-7" method="post" action=" {% url 'home_app:add-contact' %} "> {% csrf_token %}
            <div class="grid-x grid-padding-x">
                <div class="medium-6 cell">
                  <label>Nombres
                    <input type="text" placeholder="nombres..." name="full_name" id="id_full_name">
                  </label>
                </div>
                <div class="medium-6 cell">
                  <label>Correo
                    <input type="email" placeholder="Correo ..." name="email" id="id_email">
                  </label>
                </div>
                <div class="medium-12 cell">
                    <label>Mensaje
                        <textarea placeholder="Mensaje" name="message" id="id_message"></textarea>
                    </label>
                </div>
                <div class="medium-12 cell">
                    <button type="submit" class="success button">Enviar</button>
                </div>
            </div>
        </form>
        <div class="cell small-12 large-7">
          <p class="cell large-8">Otras formas de contacto:</p>
          <p class="cell large-8">
            <span class="label warning">{{ correo }}</span>
            <span class="label warning">{{ phone }}</span>
          </p>
        </div>
    </div>
  </div>
</footer>

templates/includes/header.html
<header>
    <div class="grid-x header">
        <div class="cell small-12 medium-4 large-3">
            <a href="{% url 'home_app:index' %}" style="font-size: 20px; color: #0277bd;">
                Jimmy Reyes Blog's
            </a>
        </div>
        <div class="cell small-12 medium-4">
            
        </div>
        <div class="cell small-12 large-5">
            <ul class="menu" style="justify-content: flex-end;">
                <li>
                    <a href="{% url 'home_app:index' %}">Home</a>
                </li>
                <li>
                    <a href="{% url 'entrada_app:entry-lista' %}">Blog</a>
                </li>
                <li>
                    {% if not user.is_anonymous %}
                        <a href="{% url 'favoritos_app:perfil' %} "class="warning button">Perfil</a>
                    {% else %}
                        <a href="{% url 'users_app:user-login' %} "class="success button">Acceder</a>
                    {% endif %}
                </li>
                
            </ul>
        </div>
    </div>
</header>