applications/entradas/urls.py
from django.urls import path
from . import views

app_name = "entrada_app"

urlpatterns = [
    path(
        'entradas/', 
        views.EntryListView.as_view(),
        name='entry-lista',
    ),     
    path(
        'entrada/<slug>/', 
        views.EntryDetailView.as_view(),
        name='entry-detail',
    ),  
]

applications/favoritos/urls.py
#
from django.urls import path


from . import views

app_name = "favoritos_app"

urlpatterns = [
    path(
        'perfil/', 
        views.UserPageView.as_view(),
        name='perfil',
    ),  
    path(
        'add-entrada/<pk>/', 
        views.AddFavoritos.as_view(),
        name='add-favoritos',
    ),
    path(
        'delete-entrada/<pk>/', 
        views.FavoritesDeleteView.as_view(),
        name='delete-favoritos',
    ),
]

proyectobase/urls.py
"""
Proyecto Curso Django
"""
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
# seo
from django.contrib.sitemaps.views import sitemap
from applications.home.sitemap import (
    EntrySitemap,
    Sitemap,
)

urlpatterns_main = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.entradas.urls')),
    re_path('', include('applications.favoritos.urls')),
    # urls para ckeditor
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#objeto site map que genera xml
sitemaps = {
    'site':Sitemap(
        [
            'home_app:index'
        ]
    ),
    'entradas': EntrySitemap
}

urlpatterns_sitemap = [
    path(
        'sitemap.xml', 
        sitemap, 
        {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    )
]

urlpatterns = urlpatterns_main + urlpatterns_sitemap

applications/entradas/models.py
from datetime import timedelta, datetime
# 
from django.db import models
from django.conf import settings
from django.template.defaultfilters import slugify
from django.urls import reverse_lazy

# apps terceros
from model_utils.models import TimeStampedModel
from ckeditor_uploader.fields import RichTextUploadingField

# manager
from .managers import EntryManager

# Create your models here.
class Category(TimeStampedModel):
    # Categorias de una entrada
    
    name = models.CharField(
        'Nombre',
        max_length=30
    )  
    short_name = models.CharField(
        'Nombre corto',
        max_length=15,
        unique=True
    )    
    
    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        
    def __str__(self):
        return self.name
    
class Tag(TimeStampedModel):
    # etiquetas de un articulo
    
    name = models.CharField(
        'Nombre',
        max_length=30
    )
    
    class Meta:
        verbose_name = 'Etiqueta'
        verbose_name_plural = 'Tags'
        
    def __str__(self):
        return self.name
    
class Entry(TimeStampedModel):
    # modelo para entradas o articulos
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,        
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE
    )
    tag = models.ManyToManyField(Tag)
    title = models.CharField(
        'Titulo',
        max_length=200
    )
    resume = RichTextUploadingField('Resumen')
    content = RichTextUploadingField('contenido')
    public = models.BooleanField(default=False)
    image = models.ImageField(
        'Imagen',
        upload_to='Entry',
    )
    portada = models.BooleanField(default=False)
    in_home = models.BooleanField(default=False)
    # para el seo
    slug = models.SlugField(editable=False, max_length=300)
    
    objects = EntryManager()
    
    class Meta:
        verbose_name = 'Entrada'
        verbose_name_plural = 'Entradas'        
          
    def __str__(self):
        return self.title
        
    def get_absolute_url(self):        
        return reverse_lazy(
            'entrada_app:entry-detail', 
            kwargs={
                'slug': self.slug
            }
        )
    
    def save(self, *args, **kwargs):
        # calcumalos el total de segundos da la hora actual para el slug
        now = datetime.now()
        total_time = timedelta(
            hours=now.hour,
            minutes=now.minute,
            seconds=now.second
        )
        seconds = int(total_time.total_seconds())
        slug_unique ='%s %s' % (self.title, str(seconds))
        
        self.slug = slugify(slug_unique)
        super(Entry, self).save(*args, **kwargs)

applications/entradas/views.py
from django.shortcuts import render
# 
from django.views.generic import (
    ListView,
    DetailView
)

# models
from .models import Category, Entry


# Create your views here.
class EntryListView(ListView):    
    template_name = "entrada/lista.html"
    context_object_name = 'entradas'
    paginate_by = 2
    
    
    def get_context_data(self, **kwargs):
        context = super(EntryListView, self).get_context_data(**kwargs)
        context["categorias"] = Category.objects.all()
        return context
    
    
    def get_queryset(self):
        kword = self.request.GET.get("kword", '')
        categoria = self.request.GET.get("categoria", '')
        # consulta de busqueda
        resultado = Entry.objects.buscar_entrada(kword, categoria)
        return resultado



class EntryDetailView(DetailView):
    model = Entry
    template_name = "entrada/detail.html"
    

templates/entrada/base_entrada.html
{% extends "base.html" %}

{% load  static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/myblog.css' %}">
{% endblock css %}

{% block js %}

{% endblock js %}

templates/entrada/detail boton.html
<!-- head para PC -->
{% extends "entrada/base_entrada.html" %}
{% load  static %}
{% comment %} seo titulo entradas {% endcomment %}
{% block title %}
{{entry.title}}
{% endblock title %}

{% comment %} seo resumen entradas {% endcomment %}
{% block description %}
<meta name="description" content="{{entry.resumen}}">
{% endblock description %}

{% comment %} seo tags entradas, pero no funciona en chrome {% endcomment %}
{% block tags %}
<meta name="keywords" content="
    {% for t in entry.tag.all %}
        {{ t.name }} ,
    {% endfor %}
">
{% endblock tags %}


{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x grid-margin-x" style="margin-top: 1em;">
        <h3 class="cell">{{ object.title }}</h3>        

        <!-- bloque de contenido del articulo -->
        <div class="cell large-8">
            <div class="cell callout primary">
                <h5>Resumen:</h5>
                <p>{{ entry.resume|safe }}</p>
            </div>
            <div>
                {% comment %} safe para que en el fron no salgo los codigo html {% endcomment %}
                <p>{{ entry.content|safe }}</p> 
            </div>
        </div>
        <!-- FIN bloque contenido del articulo -->

        <!-- bloque llamada a la accion -->
        <div class="cell large-4">
            <div class="card" style="width: 100%;">
                <img class="card-favoritos-img" src="{{ entry.image.url }}" style="width: 100%;">
                <div class="card-section" style="width: 100%;">
                    {% comment %} arreglar el boton de agregar clase 207 como referencia {% endcomment %}
                    {% for entrada in entradas_user %}
                        {% if not entrada in entradas_user  %}
                            <form class="blog-action" action="{% url 'favoritos_app:add-favoritos' entry.id %}" method="post"> {% csrf_token %}
                                            
                            <button type="submit" class="submit success button">Agregar a Favoritos</button>
                            
                            </form>
                        {% else %}
                            <form class="blog-action" action="{% url 'favoritos_app:delete-favoritos' entry.id %}" method="post"> {% csrf_token %}
                            
                                <button type="submit" class="submit success button" method="post" action="">Eliminar de Favoritos</button>
                                                        
                            </form>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
        <!-- FIN bloque llamada a la accion -->

    </div>
</div>
{% include "includes/footer.html" %}

{% endblock content %}

templates/entrada/detail.html
<!-- head para PC -->
{% extends "entrada/base_entrada.html" %}
{% load  static %}
{% comment %} seo titulo entradas {% endcomment %}
{% block title %}
{{entry.title}}
{% endblock title %}

{% comment %} seo resumen entradas {% endcomment %}
{% block description %}
<meta name="description" content="{{entry.resumen}}">
{% endblock description %}

{% comment %} seo tags entradas, pero no funciona en chrome {% endcomment %}
{% block tags %}
<meta name="keywords" content="
    {% for t in entry.tag.all %}
        {{ t.name }} ,
    {% endfor %}
">
{% endblock tags %}


{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x grid-margin-x" style="margin-top: 1em;">
        <h3 class="cell">{{ object.title }}</h3>                     
                
        <!-- bloque de contenido del articulo -->
        <div class="cell large-8">
            <div class="cell callout primary">
                <h5>Resumen:</h5>
                <p>{{ entry.resume|safe }}</p>
            </div>
            <div>
                {% comment %} safe para que en el fron no salgo los codigo html {% endcomment %}
                <p>{{ entry.content|safe }}</p> 
            </div>
        </div>
        <!-- FIN bloque contenido del articulo -->

        <!-- bloque llamada a la accion -->
        <div class="cell large-4">
            <div class="card" style="width: 100%;">
                <img class="card-favoritos-img" src="{{ entry.image.url }}" style="width: 100%;">
                <div class="card-section" style="width: 100%;">
                    <form class="blog-action" action="{% url 'favoritos_app:add-favoritos' entry.id %}" method="post"> {% csrf_token %}
                       {% comment %} arreglar el boton de agregar clase 207 como referencia {% endcomment %}
                        <button type="submit" class="submit success button">Agregar a Favoritos</button>
                    </form>
                </div>
            </div>
        </div>
        <!-- FIN bloque llamada a la accion -->

    </div>
</div>
{% include "includes/footer.html" %}

{% endblock content %}

templates/entrada/lista.html
<!-- head para PC -->
{% extends "entrada/base_entrada.html" %}
{% load  static %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x grid-margin-x" style="margin-top: 1em;">
        <!-- primer bloque pantalla blog -->
        <div class="cell small-12 large-8">

            <!-- bloque de buscador -->
            <form class="input-group" method="Get"> {% csrf_token %}
                <input class="input-group-field" type="text" id="kword" name="kword" placeholder="Buscar ...">
                <div class="input-group-button">
                  <input type="submit" class="button" value="Buscar">
                </div>
            </form>
            <!-- FIN bloque de formulario -->

            <!-- inicio bloque de resultados de busqueda -->
            <div class="grid-x grid-margin-x">
                
                {% for entrada in entradas %}
                <div class="cell small-6 large-4">
                    <div class="card" style="width: 100%;">
                        <a href="{% url 'entrada_app:entry-detail' entrada.slug %}">
                            <img src="{{ entrada.image.url }}" style="width: 300px;">
                        </a>
                        <div class="card-section">
                          <h4><a href="{% url 'entrada_app:entry-detail' entrada.slug %}"> {{entrada.title | truncatechars:40 }} </a></h4>
                          <p>{{ entrada.resume | truncatechars:100 }}</p>
                          <a href="{% url 'entrada_app:entry-detail' entrada.slug %}" class="submit success button"> Leer Mas </a>
                        </div>
                    </div>
                </div>  
                {% empty %}
                <h3 style="color: red;">No hay resultados</h3>
                {% endfor %}
                    
                                                 
            </div>
            <!-- FIN bloque de resultados de busqueda -->

        </div>
        <!-- FIN primer bloque pantalla blog -->


        <!-- inicio del segundo bloque - categorias -->
        <div class="cell small-12 large-4" style="height: 500px;">
            <h4>Categorias</h4>
            <ul class="vertical menu">
                
                {% for categoria in categorias %}
                <li><a href="?categoria={{categoria.short_name}}">{{categoria.name}}</a></li>
                {% endfor %}                    
                
            </ul>
        </div>
        <!-- FIN inicio del segundo bloque - categorias -->
    
    </div>

    <!-- inicio de bloque de paginacion -->
    <div class="cell">
        {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                    <li class="pagination-previous">
                        <a href="?page={{page_obj.previous_page_number}}">Atras</a>
                    </li>
                    {% endif %}                    
                    
                    {% for pagina in paginator.page_range %}

                    
                    {% if pagina == page_obj.number %}
                    <li class="current"><span class="show-for-sr">You're on page</span> {{ pagina }}</li>
                    {% else %}
                    <li class=""><a href="?page={{pagina}}">{{ pagina }}</a></li>
                    {% endif %}
                    {% endfor %}
                    
                    {% if page_obj.has_next %}
                    <li class="pagination-next">
                        <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}

    </div>
    <!-- FIN bloque de paginacion -->
</div>
{% include "includes/footer.html" %}

{% endblock content %}